# key-value pairs
id1: 'test id'
id2: 'testing 1, 2, 3'

# data sources to slurp and sequence
ci:
  url: https://whimsy.apache.org/public/committee-info.json
  board:
    description: 'Board of Directors'
    select: board.roster
  officers:
    description: 'Foundation Officers'
    select: officers
    transform: roster
  committees:
    description: 'Foundation Committees'
    select: committees
    trim: report,roster
    transform: chair
  projects:
    description: 'Current Projects'
    select: committees
    trim: report,roster
    transform: chair
    filter: pmc
  featured_projs:
    description: 'Featured Projects'
    sequence: projects
    random: 3

pods:
  url: https://projects.apache.org/json/foundation/podlings.json
  podlings:
    description: 'Current Podlings'
  featured_pods:
    description: 'Featured Podlings'
    sequence: podlings
    random: 3
